import json
import re

seed_data_path = '/Users/maggi/kavya_pickles/src/lib/data/seed-data.ts'

categories_code = '''import { Category, Product, Order, Coupon, Review, Customer, StoreSettings, FlashUpdate } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-veg',
    name: 'Veg Pickles',
    slug: 'veg-pickles',
    description: 'Authentic homemade vegetarian pickles crafted with traditional recipes and premium ingredients.',
    image_url: '/images/pickles/avakaya.jpg',
    is_active: true,
    display_order: 1,
  },
  {
    id: 'cat-nonveg',
    name: 'Authentic Non-Veg Pickles',
    slug: 'authentic-non-veg-pickles',
    description: 'Slow-cooked succulent meat & seafood pickles prepared with age-old royal recipes.',
    image_url: '/images/pickles/chicken.jpg',
    is_active: true,
    display_order: 2,
  },
  {
    id: 'cat-andhra',
    name: 'Spicy Andhra Delights',
    slug: 'spicy-andhra-delights',
    description: 'Fiery and bold flavors from the heart of Andhra Pradesh, famous for Guntur chillies and gongura.',
    image_url: '/images/pickles/gongura.jpg',
    is_active: true,
    display_order: 3,
  },
  {
    id: 'cat-seasonal',
    name: 'Seasonal & Gourmet Specials',
    slug: 'seasonal-gourmet-specials',
    description: 'Limited edition small-batch batches made with fresh seasonal produce like wild gooseberries and winter veggies.',
    image_url: '/images/pickles/garlic.jpg',
    is_active: true,
    display_order: 4,
  },
  {
    id: 'cat-combos',
    name: 'Handcrafted Combo Jars',
    slug: 'handcrafted-combo-jars',
    description: 'Curated value packs and gift sets of our most loved homemade pickle varieties.',
    image_url: '/images/pickles/hero.jpg',
    is_active: true,
    display_order: 5,
  },
];
'''

veg_products = [
  {
    "id": "prod-avakaya",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Avakaya Pickle",
    "slug": "avakaya-pickle",
    "short_description": "Authentic Andhra raw mango avakaya pickle made with stone-ground Guntur chillies & cold-pressed sesame oil.",
    "description": "Our traditional Avakaya Pickle is crafted with fresh, hand-cut raw Ramkela mangoes, sun-cured with stone-ground Guntur red chillies, fragrant mustard powder, garlic, and pure gingelly oil following an authentic heirloom Andhra recipe.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 60,
    "sku": "KP-AVK-250",
    "spice_level": "Extra Hot",
    "dietary": "veg",
    "shelf_life": "12 Months",
    "storage_instructions": "Store in a cool dry place. Always use a dry spoon.",
    "ingredients": ["Raw Mango Pieces", "Cold-Pressed Sesame Oil", "Guntur Red Chilli Powder", "Mustard Powder", "Garlic", "Sea Salt", "Turmeric"],
    "images": ["/images/pickles/avakaya.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.9,
    "reviews_count": 152,
    "variants": [
      { "id": "var-avk-250", "product_id": "prod-avakaya", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 60 },
      { "id": "var-avk-500", "product_id": "prod-avakaya", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 35 },
      { "id": "var-avk-1kg", "product_id": "prod-avakaya", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 20 }
    ],
    "created_at": "2026-08-01T10:00:00Z"
  },
  {
    "id": "prod-tomato",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Tomato Pickle",
    "slug": "tomato-pickle",
    "short_description": "Rich red country tomato pickle slow-simmered with tamarind pulp, mustard, and curry leaves.",
    "description": "Juicy vine-ripened tomatoes slow-reduced with tamarind, red chilli oil, mustard seeds, and fried curry leaves to create a rich savory tomato thokku pickle perfect with hot rice, idlis, and parathas.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 50,
    "sku": "KP-TOM-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "9 Months",
    "storage_instructions": "Store in a cool dry place. Use a clean dry spoon.",
    "ingredients": ["Country Desi Tomatoes", "Tamarind Pulp", "Sesame Oil", "Red Chilli Powder", "Mustard Seeds", "Curry Leaves", "Asafoetida", "Salt"],
    "images": ["/images/pickles/tomato.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.8,
    "reviews_count": 88,
    "variants": [
      { "id": "var-tom-250", "product_id": "prod-tomato", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 50 },
      { "id": "var-tom-500", "product_id": "prod-tomato", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 30 },
      { "id": "var-tom-1kg", "product_id": "prod-tomato", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 15 }
    ],
    "created_at": "2026-08-02T10:00:00Z"
  },
  {
    "id": "prod-pandu-mirchi",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Pandu Mirchi Pickle",
    "slug": "pandu-mirchi-pickle",
    "short_description": "Fiery Andhra red chilli pickle made from ripe red chillies, tamarind, and garlic.",
    "description": "Authentic Andhra Pandu Mirchi Pachadi crafted with freshly harvested ripe red chillies coarsely ground with wild tamarind, plump garlic cloves, and cold-pressed gingelly oil for an unmatched spicy explosion.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 45,
    "sku": "KP-PND-250",
    "spice_level": "Extra Hot",
    "dietary": "veg",
    "shelf_life": "12 Months",
    "storage_instructions": "Keep jar lid closed tightly. Keep away from direct sunlight.",
    "ingredients": ["Ripe Red Chillies", "Tamarind", "Garlic", "Sesame Oil", "Mustard Seeds", "Salt", "Fenugreek"],
    "images": ["/images/pickles/pandu_mirchi.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.9,
    "reviews_count": 110,
    "variants": [
      { "id": "var-pnd-250", "product_id": "prod-pandu-mirchi", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 45 },
      { "id": "var-pnd-500", "product_id": "prod-pandu-mirchi", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 25 },
      { "id": "var-pnd-1kg", "product_id": "prod-pandu-mirchi", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 12 }
    ],
    "created_at": "2026-08-03T10:00:00Z"
  },
  {
    "id": "prod-gongura",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Gongura Pickle",
    "slug": "gongura-pickle",
    "short_description": "Authentic tangy sorrel leaf pickle slow-roasted with roasted red chillies and garlic.",
    "description": "Handpicked fresh red sorrel leaves slow-cooked in fragrant cold-pressed sesame oil, tempered with sun-dried red chillies, garlic, and fenugreek. Delivers the legendary tangy Andhra taste.",
    "price": 600,
    "mrp": 699,
    "discount_percent": 14,
    "weight": "250g",
    "stock_quantity": 50,
    "sku": "KP-GON-250",
    "spice_level": "Hot",
    "dietary": "veg",
    "shelf_life": "9 Months",
    "storage_instructions": "Store at room temperature. Keep submerged in spiced oil.",
    "ingredients": ["Sorrel (Gongura) Leaves", "Sesame Oil", "Dry Red Chillies", "Garlic", "Mustard", "Fenugreek", "Salt"],
    "images": ["/images/pickles/gongura.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.8,
    "reviews_count": 125,
    "variants": [
      { "id": "var-gon-250", "product_id": "prod-gongura", "weight": "250g", "price": 600, "mrp": 699, "stock_quantity": 50 },
      { "id": "var-gon-500", "product_id": "prod-gongura", "weight": "500g", "price": 1099, "mrp": 1249, "stock_quantity": 30 },
      { "id": "var-gon-1kg", "product_id": "prod-gongura", "weight": "1kg", "price": 1999, "mrp": 2299, "stock_quantity": 15 }
    ],
    "created_at": "2026-08-04T10:00:00Z"
  },
  {
    "id": "prod-nimmakaya",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Nimmakaya Pickle",
    "slug": "nimmakaya-pickle",
    "short_description": "Traditional sun-cured yellow lemon pickle with spicy salt seasoning & mustard seeds.",
    "description": "Fresh kagzi lemons sun-cured for 21 days with rock salt, yellow mustard, and spicy red chilli powder to create a lip-smacking digestion-boosting tangy lemon pickle.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 55,
    "sku": "KP-NMK-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "18 Months",
    "storage_instructions": "Store in a dry place. Gets better with age.",
    "ingredients": ["Yellow Lemons", "Red Chilli Powder", "Mustard Seeds", "Carom Seeds", "Turmeric", "Rock Salt"],
    "images": ["/images/pickles/nimmakaya.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.7,
    "reviews_count": 75,
    "variants": [
      { "id": "var-nmk-250", "product_id": "prod-nimmakaya", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 55 },
      { "id": "var-nmk-500", "product_id": "prod-nimmakaya", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 30 },
      { "id": "var-nmk-1kg", "product_id": "prod-nimmakaya", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 15 }
    ],
    "created_at": "2026-08-05T10:00:00Z"
  },
  {
    "id": "prod-dabbakaya",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Dabbakaya Pickle",
    "slug": "dabbakaya-pickle",
    "short_description": "Authentic South Indian citron pickle seasoned with fenugreek & roasted mustard oil.",
    "description": "Hand-harvested Indian citron (Dabbakaya) cured with traditional spices, split fenugreek, mustard, and gingelly oil, offering a rare combination of citrus aroma and savory spice.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 40,
    "sku": "KP-DBK-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "12 Months",
    "storage_instructions": "Keep jar closed tight in a dry cool place.",
    "ingredients": ["Citron (Dabbakaya)", "Gingelly Oil", "Red Chilli Powder", "Mustard Powder", "Fenugreek", "Salt"],
    "images": ["/images/pickles/dabbakaya.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.8,
    "reviews_count": 62,
    "variants": [
      { "id": "var-dbk-250", "product_id": "prod-dabbakaya", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 40 },
      { "id": "var-dbk-500", "product_id": "prod-dabbakaya", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 20 },
      { "id": "var-dbk-1kg", "product_id": "prod-dabbakaya", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 10 }
    ],
    "created_at": "2026-08-06T10:00:00Z"
  },
  {
    "id": "prod-vendu-mirchi-gongura",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Vendu Mirchi Gongura Pickle",
    "slug": "vendu-mirchi-gongura-pickle",
    "short_description": "Sun-dried red chillies blended with Gongura sorrel leaves and garlic.",
    "description": "Crisp sun-dried whole red chillies braised with sour Gongura sorrel leaves, roasted mustard seeds, garlic, and sesame oil to create a fiery regional Andhra favorite.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 48,
    "sku": "KP-VMG-250",
    "spice_level": "Extra Hot",
    "dietary": "veg",
    "shelf_life": "9 Months",
    "storage_instructions": "Keep in a dry container. Use dry spoon.",
    "ingredients": ["Dried Red Chillies", "Sorrel (Gongura) Leaves", "Garlic", "Sesame Oil", "Mustard", "Salt"],
    "images": ["/images/pickles/vendu_mirchi_gongura.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.9,
    "reviews_count": 82,
    "variants": [
      { "id": "var-vmg-250", "product_id": "prod-vendu-mirchi-gongura", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 48 },
      { "id": "var-vmg-500", "product_id": "prod-vendu-mirchi-gongura", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 28 },
      { "id": "var-vmg-1kg", "product_id": "prod-vendu-mirchi-gongura", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 12 }
    ],
    "created_at": "2026-08-07T10:00:00Z"
  },
  {
    "id": "prod-allam",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Allam Pickle",
    "slug": "allam-pickle",
    "short_description": "Rich Andhra ginger pickle with tamarind, organic jaggery, and spices.",
    "description": "Freshly grated ginger root slow-cooked with thick tamarind pulp, organic dark jaggery, red chilli powder, and sesame oil tempering. Perfectly balances sweet, tangy, and spicy notes.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 50,
    "sku": "KP-ALM-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "9 Months",
    "storage_instructions": "Store in a cool place away from moisture.",
    "ingredients": ["Fresh Ginger Root", "Tamarind", "Jaggery", "Red Chilli Powder", "Sesame Oil", "Salt"],
    "images": ["/images/pickles/allam.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.8,
    "reviews_count": 95,
    "variants": [
      { "id": "var-alm-250", "product_id": "prod-allam", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 50 },
      { "id": "var-alm-500", "product_id": "prod-allam", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 30 },
      { "id": "var-alm-1kg", "product_id": "prod-allam", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 14 }
    ],
    "created_at": "2026-08-08T10:00:00Z"
  },
  {
    "id": "prod-pudina",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Pudina Pickle",
    "slug": "pudina-pickle",
    "short_description": "Fresh mint leaf pickle seasoned with garlic, tamarind, and cold-pressed oil.",
    "description": "Aromatic fresh garden mint (pudina) leaves roasted with green chillies, tamarind pulp, garlic cloves, and gingelly oil, creating a refreshing yet zesty pickle.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 42,
    "sku": "KP-PDN-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "6 Months",
    "storage_instructions": "Keep refrigerated after opening for optimal freshness.",
    "ingredients": ["Fresh Mint Leaves", "Garlic", "Tamarind", "Green Chillies", "Sesame Oil", "Salt"],
    "images": ["/images/pickles/pudina.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.7,
    "reviews_count": 68,
    "variants": [
      { "id": "var-pdn-250", "product_id": "prod-pudina", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 42 },
      { "id": "var-pdn-500", "product_id": "prod-pudina", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 22 },
      { "id": "var-pdn-1kg", "product_id": "prod-pudina", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 10 }
    ],
    "created_at": "2026-08-09T10:00:00Z"
  },
  {
    "id": "prod-kothimira",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Kothimira Pickle",
    "slug": "kothimira-pickle",
    "short_description": "Fresh coriander cilantro leaf pickle with tamarind, garlic, and spices.",
    "description": "Farm-fresh green coriander (cilantro) leaves ground coarsely with tamarind, garlic, red chillies, and tempered in pure cold-pressed oil for an invigorating taste.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 40,
    "sku": "KP-KTM-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "6 Months",
    "storage_instructions": "Store in a dry place. Keep spoon clean.",
    "ingredients": ["Fresh Coriander Leaves", "Tamarind", "Garlic", "Red Chilli Powder", "Sesame Oil", "Salt"],
    "images": ["/images/pickles/kothimira.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.7,
    "reviews_count": 54,
    "variants": [
      { "id": "var-ktm-250", "product_id": "prod-kothimira", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 40 },
      { "id": "var-ktm-500", "product_id": "prod-kothimira", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 20 },
      { "id": "var-ktm-1kg", "product_id": "prod-kothimira", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 10 }
    ],
    "created_at": "2026-08-10T10:00:00Z"
  },
  {
    "id": "prod-chintakaya",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Chintakaya Pickle",
    "slug": "chintakaya-pickle",
    "short_description": "Authentic raw green tamarind pickle crushed with green chillies & mustard temper.",
    "description": "Tender raw green tamarind pods crushed with green chillies, turmeric, salt, and seasoned with mustard-curry leaf tempering. A legendary tangy rustic delicacy.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 45,
    "sku": "KP-CHK-250",
    "spice_level": "Hot",
    "dietary": "veg",
    "shelf_life": "12 Months",
    "storage_instructions": "Store in glass or ceramic jar.",
    "ingredients": ["Raw Green Tamarind Pods", "Green Chillies", "Turmeric", "Sesame Oil", "Mustard Seeds", "Salt"],
    "images": ["/images/pickles/chintakaya.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.8,
    "reviews_count": 79,
    "variants": [
      { "id": "var-ctk-250", "product_id": "prod-chintakaya", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 45 },
      { "id": "var-ctk-500", "product_id": "prod-chintakaya", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 25 },
      { "id": "var-ctk-1kg", "product_id": "prod-chintakaya", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 12 }
    ],
    "created_at": "2026-08-11T10:00:00Z"
  },
  {
    "id": "prod-usiri",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Usiri Pickle",
    "slug": "usiri-pickle",
    "short_description": "Whole Indian gooseberry (amla) pickle infused with red chilli mustard spice.",
    "description": "Plump whole Indian amla gooseberries steamed and cured in spicy Guntur red chilli powder, stone-ground mustard, fenugreek, and cold-pressed gingelly oil.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 50,
    "sku": "KP-USR-250",
    "spice_level": "Hot",
    "dietary": "veg",
    "shelf_life": "12 Months",
    "storage_instructions": "Store in a cool dry pantry. Keeps amla fresh.",
    "ingredients": ["Whole Indian Amla Gooseberries", "Red Chilli Powder", "Mustard Powder", "Fenugreek", "Sesame Oil", "Salt"],
    "images": ["/images/pickles/usiri.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.9,
    "reviews_count": 102,
    "variants": [
      { "id": "var-usr-250", "product_id": "prod-usiri", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 50 },
      { "id": "var-usr-500", "product_id": "prod-usiri", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 30 },
      { "id": "var-usr-1kg", "product_id": "prod-usiri", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 15 }
    ],
    "created_at": "2026-08-12T10:00:00Z"
  },
  {
    "id": "prod-mamidi-thokku",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Mamidi Thokku Pickle",
    "slug": "mamidi-thokku-pickle",
    "short_description": "Shredded raw mango thokku pickle with red chilli powder & garlic.",
    "description": "Finely grated raw green mango strands marinated with spicy red chillies, garlic, mustard seeds, and sesame oil. Spreads effortlessly over warm rice and flatbreads.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 52,
    "sku": "KP-MTK-250",
    "spice_level": "Hot",
    "dietary": "veg",
    "shelf_life": "12 Months",
    "storage_instructions": "Store tightly closed in cool dark space.",
    "ingredients": ["Grated Raw Green Mango", "Red Chilli Powder", "Garlic", "Mustard Powder", "Sesame Oil", "Salt"],
    "images": ["/images/pickles/mamidi_thokku.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.8,
    "reviews_count": 84,
    "variants": [
      { "id": "var-mtk-250", "product_id": "prod-mamidi-thokku", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 52 },
      { "id": "var-mtk-500", "product_id": "prod-mamidi-thokku", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 32 },
      { "id": "var-mtk-1kg", "product_id": "prod-mamidi-thokku", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 14 }
    ],
    "created_at": "2026-08-13T10:00:00Z"
  },
  {
    "id": "prod-kakarakaya",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Kakarakaya Pickle",
    "slug": "kakarakaya-pickle",
    "short_description": "Crispy bitter gourd pickle cooked with tamarind, jaggery, and aromatic spices.",
    "description": "Crisp-fried bitter gourd roundels folded into a rich tamarind, jaggery, and red chilli masala gravy. The unique balance of bitter, sweet, sour, and spicy makes it a gourmet treat.",
    "price": 600,
    "mrp": 699,
    "discount_percent": 14,
    "weight": "250g",
    "stock_quantity": 40,
    "sku": "KP-KKA-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "9 Months",
    "storage_instructions": "Keep jar dry. Use a clean dry spoon.",
    "ingredients": ["Bitter Gourd (Kakarakaya)", "Tamarind", "Jaggery", "Red Chilli Powder", "Sesame Oil", "Salt"],
    "images": ["/images/pickles/kakarakaya.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.7,
    "reviews_count": 61,
    "variants": [
      { "id": "var-kka-250", "product_id": "prod-kakarakaya", "weight": "250g", "price": 600, "mrp": 699, "stock_quantity": 40 },
      { "id": "var-kka-500", "product_id": "prod-kakarakaya", "weight": "500g", "price": 1099, "mrp": 1249, "stock_quantity": 20 },
      { "id": "var-kka-1kg", "product_id": "prod-kakarakaya", "weight": "1kg", "price": 1999, "mrp": 2299, "stock_quantity": 10 }
    ],
    "created_at": "2026-08-14T10:00:00Z"
  },
  {
    "id": "prod-vellulli",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Vellulli Pickle",
    "slug": "vellulli-pickle",
    "short_description": "Whole garlic clove pickle drenched in mustard oil and roasted Indian spices.",
    "description": "Immunity-boosting whole peeled garlic cloves soaked in cold-pressed mustard oil, crushed yellow mustard, and spicy Guntur red chilli powder.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 50,
    "sku": "KP-VEL-250",
    "spice_level": "Hot",
    "dietary": "veg",
    "shelf_life": "12 Months",
    "storage_instructions": "Keep jar tightly closed in a cool dry area.",
    "ingredients": ["Peeled Whole Garlic Cloves", "Mustard Oil", "Red Chilli Powder", "Mustard Seeds", "Fenugreek", "Salt"],
    "images": ["/images/pickles/vellulli.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.8,
    "reviews_count": 98,
    "variants": [
      { "id": "var-vel-250", "product_id": "prod-vellulli", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 50 },
      { "id": "var-vel-500", "product_id": "prod-vellulli", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 30 },
      { "id": "var-vel-1kg", "product_id": "prod-vellulli", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 15 }
    ],
    "created_at": "2026-08-15T10:00:00Z"
  },
  {
    "id": "prod-munagakaya",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Munagakaya Pickle",
    "slug": "munagakaya-pickle",
    "short_description": "Tender drumstick pickle cooked in spicy Andhra tamarind mustard marinade.",
    "description": "Fresh cut drumstick (munagakaya) pieces marinated in fiery Andhra red chilli masala, tamarind pulp, and tempered in pure sesame oil.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 40,
    "sku": "KP-MNK-250",
    "spice_level": "Hot",
    "dietary": "veg",
    "shelf_life": "6 Months",
    "storage_instructions": "Refrigerate after opening for extended freshness.",
    "ingredients": ["Drumstick Pieces", "Tamarind Pulp", "Red Chilli Powder", "Sesame Oil", "Mustard Seeds", "Salt"],
    "images": ["/images/pickles/munagakaya.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.7,
    "reviews_count": 52,
    "variants": [
      { "id": "var-mnk-250", "product_id": "prod-munagakaya", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 40 },
      { "id": "var-mnk-500", "product_id": "prod-munagakaya", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 20 },
      { "id": "var-mnk-1kg", "product_id": "prod-munagakaya", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 10 }
    ],
    "created_at": "2026-08-16T10:00:00Z"
  },
  {
    "id": "prod-karivepaku",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Karivepaku Pickle",
    "slug": "karivepaku-pickle",
    "short_description": "Fragrant curry leaf pickle coarsely ground with tamarind, garlic & gingelly oil.",
    "description": "Fresh, dark green curry leaves dry-roasted and coarsely ground with roasted red chillies, tamarind, garlic, and sesame oil. Rich in iron and digestive wellness.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 45,
    "sku": "KP-KVP-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "9 Months",
    "storage_instructions": "Store in a cool dry place. Keep jar tightly closed.",
    "ingredients": ["Fresh Curry Leaves", "Tamarind", "Garlic", "Red Chilli Powder", "Sesame Oil", "Salt"],
    "images": ["/images/pickles/karivepaku.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.8,
    "reviews_count": 71,
    "variants": [
      { "id": "var-kvp-250", "product_id": "prod-karivepaku", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 45 },
      { "id": "var-kvp-500", "product_id": "prod-karivepaku", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 25 },
      { "id": "var-kvp-1kg", "product_id": "prod-karivepaku", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 12 }
    ],
    "created_at": "2026-08-17T10:00:00Z"
  },
  {
    "id": "prod-maagaya",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Maagaya Pickle",
    "slug": "maagaya-pickle",
    "short_description": "Sun-dried raw mango slice pickle with fenugreek & mustard oil.",
    "description": "Peeled raw mango strips sun-dried and cured with roasted fenugreek powder, Guntur red chilli powder, turmeric, and gingelly oil for an authentic vintage Andhra flavor.",
    "price": 600,
    "mrp": 699,
    "discount_percent": 14,
    "weight": "250g",
    "stock_quantity": 40,
    "sku": "KP-MGY-250",
    "spice_level": "Hot",
    "dietary": "veg",
    "shelf_life": "12 Months",
    "storage_instructions": "Store in ceramic martaban or glass jar.",
    "ingredients": ["Peeled Raw Mango Strips", "Fenugreek Powder", "Red Chilli Powder", "Sesame Oil", "Mustard", "Salt"],
    "images": ["/images/pickles/maagaya.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.9,
    "reviews_count": 90,
    "variants": [
      { "id": "var-mgy-250", "product_id": "prod-maagaya", "weight": "250g", "price": 600, "mrp": 699, "stock_quantity": 40 },
      { "id": "var-mgy-500", "product_id": "prod-maagaya", "weight": "500g", "price": 1099, "mrp": 1249, "stock_quantity": 20 },
      { "id": "var-mgy-1kg", "product_id": "prod-maagaya", "weight": "1kg", "price": 1999, "mrp": 2299, "stock_quantity": 10 }
    ],
    "created_at": "2026-08-18T10:00:00Z"
  },
  {
    "id": "prod-all-veg-mixed",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "All Veg Mixed Pickle",
    "slug": "all-veg-mixed-pickle",
    "short_description": "Assorted farm vegetables cured in traditional Indian red chilli mustard spice oil.",
    "description": "A delicious medley of diced raw mangoes, carrots, green chillies, cauliflower, and lime cured in a fragrant red chilli and yellow mustard oil blend.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 55,
    "sku": "KP-MXV-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "12 Months",
    "storage_instructions": "Store in a cool dry location.",
    "ingredients": ["Raw Mango", "Carrots", "Cauliflower", "Green Chillies", "Lime", "Mustard Oil", "Spices", "Salt"],
    "images": ["/images/pickles/all_veg_mixed.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.8,
    "reviews_count": 85,
    "variants": [
      { "id": "var-mxv-250", "product_id": "prod-all-veg-mixed", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 55 },
      { "id": "var-mxv-500", "product_id": "prod-all-veg-mixed", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 35 },
      { "id": "var-mxv-1kg", "product_id": "prod-all-veg-mixed", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 18 }
    ],
    "created_at": "2026-08-19T10:00:00Z"
  },
  {
    "id": "prod-cauliflower",
    "category_id": "cat-veg",
    "category_name": "Veg Pickles",
    "name": "Cauliflower Pickle",
    "slug": "cauliflower-pickle",
    "short_description": "Crunchy cauliflower florets pickled with mustard, ginger, and Kashmiri chilli.",
    "description": "Fresh crispy white cauliflower florets blanched and marinated in Kashmiri red chilli, ginger, yellow mustard powder, and mustard oil for a crunchy gourmet pickle experience.",
    "price": 400,
    "mrp": 499,
    "discount_percent": 20,
    "weight": "250g",
    "stock_quantity": 45,
    "sku": "KP-CLF-250",
    "spice_level": "Medium",
    "dietary": "veg",
    "shelf_life": "6 Months",
    "storage_instructions": "Keep jar closed tight in cool dry place.",
    "ingredients": ["Cauliflower Florets", "Mustard Oil", "Kashmiri Red Chilli", "Yellow Mustard", "Ginger", "Salt"],
    "images": ["/images/pickles/cauliflower.jpg"],
    "is_featured": False,
    "is_active": True,
    "rating": 4.7,
    "reviews_count": 64,
    "variants": [
      { "id": "var-clf-250", "product_id": "prod-cauliflower", "weight": "250g", "price": 400, "mrp": 499, "stock_quantity": 45 },
      { "id": "var-clf-500", "product_id": "prod-cauliflower", "weight": "500g", "price": 749, "mrp": 899, "stock_quantity": 25 },
      { "id": "var-clf-1kg", "product_id": "prod-cauliflower", "weight": "1kg", "price": 1399, "mrp": 1599, "stock_quantity": 12 }
    ],
    "created_at": "2026-08-20T10:00:00Z"
  }
]

non_veg_products = [
  {
    "id": "prod-chicken",
    "category_id": "cat-nonveg",
    "category_name": "Authentic Non-Veg Pickles",
    "name": "Country Style Boneless Chicken Pickle",
    "slug": "country-style-chicken-pickle",
    "short_description": "Crisp-fried juicy tender boneless chicken bites tossed in fiery Andhra masala gravy.",
    "description": "An absolute non-veg delicacy! Fresh boneless chicken cubes are marinated in lemon juice and organic turmeric, crisp-fried till golden, and folded into a rich gravy.",
    "price": 349,
    "mrp": 399,
    "discount_percent": 13,
    "weight": "250g",
    "stock_quantity": 38,
    "sku": "KP-CHK-250",
    "spice_level": "Hot",
    "dietary": "non-veg",
    "shelf_life": "6 Months",
    "storage_instructions": "Refrigeration recommended after opening.",
    "ingredients": ["Fresh Boneless Chicken", "Cold-Pressed Oil", "Ginger-Garlic Paste", "Red Chilli Powder", "Spices", "Salt"],
    "images": ["/images/pickles/chicken.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.9,
    "reviews_count": 196,
    "variants": [
      { "id": "var-chk-250", "product_id": "prod-chicken", "weight": "250g", "price": 349, "mrp": 399, "stock_quantity": 38 },
      { "id": "var-chk-500", "product_id": "prod-chicken", "weight": "500g", "price": 599, "mrp": 699, "stock_quantity": 25 },
      { "id": "var-chk-1kg", "product_id": "prod-chicken", "weight": "1kg", "price": 1099, "mrp": 1249, "stock_quantity": 12 }
    ],
    "created_at": "2026-08-10T12:00:00Z"
  },
  {
    "id": "prod-mutton",
    "category_id": "cat-nonveg",
    "category_name": "Authentic Non-Veg Pickles",
    "name": "Royal Hyderabadi Mutton Pickle (Gosht ka Achar)",
    "slug": "royal-hyderabadi-mutton-pickle",
    "short_description": "Tender boneless mutton cubes slow-braised in aromatic Nizami roasted spices.",
    "description": "Boneless morsels of fresh, tender mutton slow-braised in their own juices and infused with Tellicherry black pepper and roasted Kashmiri chillies.",
    "price": 449,
    "mrp": 499,
    "discount_percent": 10,
    "weight": "250g",
    "stock_quantity": 24,
    "sku": "KP-MTN-250",
    "spice_level": "Hot",
    "dietary": "non-veg",
    "shelf_life": "6 Months",
    "storage_instructions": "Refrigeration recommended after opening.",
    "ingredients": ["Boneless Mutton", "Mustard Oil", "Black Pepper", "Red Chilli", "Ginger-Garlic", "Spices"],
    "images": ["/images/pickles/mutton.jpg"],
    "is_featured": True,
    "is_active": True,
    "rating": 4.9,
    "reviews_count": 145,
    "variants": [
      { "id": "var-mtn-250", "product_id": "prod-mutton", "weight": "250g", "price": 449, "mrp": 499, "stock_quantity": 24 },
      { "id": "var-mtn-500", "product_id": "prod-mutton", "weight": "500g", "price": 799, "mrp": 899, "stock_quantity": 15 },
      { "id": "var-mtn-1kg", "product_id": "prod-mutton", "weight": "1kg", "price": 1499, "mrp": 1699, "stock_quantity": 8 }
    ],
    "created_at": "2026-08-20T10:00:00Z"
  }
]

all_products = veg_products + non_veg_products

with open(seed_data_path, 'r') as f:
    content = f.read()

orders_idx = content.find('export const INITIAL_ORDERS')
rest_of_file = content[orders_idx:] if orders_idx != -1 else ''

output_code = categories_code + '\nexport const INITIAL_PRODUCTS: Product[] = ' + json.dumps(all_products, indent=2) + ';\n\n' + rest_of_file

with open(seed_data_path, 'w') as f:
    f.write(output_code)

print('Updated seed-data.ts with all 20 veg pickles!')
